apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
  labels:
    app: django-app
spec:
  replicas: 3  # Defines the number of pod replicas.
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: kabita0009/azure_devops:latest  # Docker image with Django app
        ports:
        - containerPort: 8000  # Expose the Django app on port 8000.
        readinessProbe:  # Optional readiness probe to ensure the app is ready to receive traffic.
          httpGet:
            path: "/"
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:  # Optional liveness probe to check if the app is running.
          httpGet:
            path: "/"
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: django-app-service
spec:
  selector:
    app: django-app
  ports:
  - protocol: TCP
    port: 80  # The port exposed to the outside.
    targetPort: 8000  # The port where the app listens inside the container.
  type: LoadBalancer  # LoadBalancer to expose the app publicly.
