apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
  labels:
    app: elasticsearch
spec:
  replicas: 1  # Adjust the replica count based on your cluster size
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2  # Version of Elasticsearch
        ports:
        - containerPort: 9200  # Default HTTP port for Elasticsearch
        - containerPort: 9300  # Transport port for Elasticsearch (used for inter-node communication)
        env:
        - name: discovery.type
          value: single-node  # Set single-node mode for a basic setup
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
          requests:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  selector:
    app: elasticsearch
  ports:
  - protocol: TCP
    port: 9200  # External port to access Elasticsearch HTTP API
    targetPort: 9200  # The container's internal port
  - protocol: TCP
    port: 9300  # External port to access Elasticsearch transport
    targetPort: 9300  # The container's internal port
  type: ClusterIP  # Accessible within the cluster only
